from typing import Protocol


class Channel(Protocol):
    async def connect(self) -> None: ...
    async def receive(self) -> str: ...
    async def send(self, reply: str) -> None: ...
    async def close(self) -> None: ...
